use projet_cir2;
-- _______________________ Departements __________________________--
INSERT INTO `departement`(`numero`, `nom_departement`, `nom_region`)
VALUES

    (31, "Haute-Garonne", "Occitanie"), (34, "Hérault", "Languedoc-Roussillon Midi-Pyrénées"), (26, "Drôme", "Auvergne-Rhône-Alpes"), (31, "Haute-Garonne", "Languedoc-Roussillon Midi-Pyrénées"),
    (49, "Maine-et-Loire", "Pays de la Loire"), (42, "Loire", "Auvergne-Rhône-Alpes"), (13, "Bouches-du-Rhône", "Provence-Alpes-Côte d'Azur"), (38, "Isère", "Auvergne-Rhône-Alpes"), (54, "Meurthe-et-Moselle", "Grand Est"),
    (91, "Essonne", "Île-de-France"), (30, "Gard", "Languedoc-Roussillon Midi-Pyrénées"), (84, "Vaucluse", "Provence-Alpes-Côte d'Azur"), (11, "Aude", "Languedoc-Roussillon Midi-Pyrénées"), (69, "Rhône", "Auvergne-Rhône-Alpes"),
    (71, "Saône-et-Loire", "Bourgogne Franche-Comté"), (82, "Tarn-et-Garonne", "Languedoc-Roussillon Midi-Pyrénées"), (44, "Loire-Atlantique", "Pays de la Loire"), (57, "Moselle", "Grand Est"), (33, "Gironde", "Aquitaine-Limousin-Poitou-Charentes"),
    (09, "Ariège", "Languedoc-Roussillon Midi-Pyrénées"), (73, "Savoie", "Auvergne-Rhône-Alpes"), (74, "Haute-Savoie", "Auvergne-Rhône-Alpes"), (82, "Tarn-et-Garonne", "Occitanie"), (63, "Puy-de-Dôme", "Auvergne-Rhône-Alpes"),
    (46, "Lot", "Languedoc-Roussillon Midi-Pyrénées"), (72, "Sarthe", "Pays de la Loire"), (89, "Yonne", "Bourgogne Franche-Comté"), (17, "Charente-Maritime", "Aquitaine-Limousin-Poitou-Charentes"), (59, "Nord", "Nord-Pas-de-Calais Picardie"),
    (83, "Var", "Provence-Alpes-Côte d'Azur"), (22, "Côtes-d'Armor", "Bretagne"), (81, "Tarn", "Languedoc-Roussillon Midi-Pyrénées"), (95, "Val-d'Oise", "Île-de-France"), (32, "Gers", "Languedoc-Roussillon Midi-Pyrénées"),
    (78, "Yvelines", "Île-de-France"), (76, "Seine-Maritime", "Normandie"), (57, "Moselle", "Alsace-Champagne-Ardenne-Lorraine"), (62, "Pas-de-Calais", "Nord-Pas-de-Calais Picardie"), (06, "Alpes-Maritimes", "Provence-Alpes-Côte d'Azur"),
    (92, "Hauts-de-Seine", "Île-de-France"), (02, "Aisne", "Nord-Pas-de-Calais Picardie"), (88, "Vosges", "Alsace-Champagne-Ardenne-Lorraine"), (67, "Bas-Rhin", "Alsace-Champagne-Ardenne-Lorraine"), (54, "Meurthe-et-Moselle", "Alsace-Champagne-Ardenne-Lorraine"),
    (25, "Doubs", "Bourgogne Franche-Comté"), (64, "Pyrénées-Atlantiques", "Aquitaine-Limousin-Poitou-Charentes"), (53, "Mayenne", "Pays de la Loire"), (85, "Vendée", "Pays de la Loire"), (68, "Haut-Rhin", "Alsace-Champagne-Ardenne-Lorraine"),
    (65, "Hautes-Pyrénées", "Languedoc-Roussillon Midi-Pyrénées"), (79, "Deux-Sèvres", "Aquitaine-Limousin-Poitou-Charentes"), (19, "Corrèze", "Aquitaine-Limousin-Poitou-Charentes"), (60, "Oise", "Nord-Pas-de-Calais Picardie"), (30, "Gard", "Occitanie"),
    (20, "Haute-Corse", "Corse"), (75, "Paris", "Île-de-France"), (56, "Morbihan", "Bretagne"), (37, "Indre-et-Loire", "Centre-Val de Loire"), (43, "Haute-Loire", "Auvergne-Rhône-Alpes"),
    (15, "Cantal", "Auvergne-Rhône-Alpes"), (17, "Charente-Maritime", "Nouvelle-Aquitaine"), (51, "Marne", "Alsace-Champagne-Ardenne-Lorraine"), (21, "Côte-d'Or", "Bourgogne Franche-Comté"), (66, "Pyrénées-Orientales", "Languedoc-Roussillon Midi-Pyrénées"),
    (01, "Ain", "Auvergne-Rhône-Alpes"), (70, "Haute-Saône", "Bourgogne Franche-Comté"), (08, "Ardennes", "Alsace-Champagne-Ardenne-Lorraine"), (35, "Ille-et-Vilaine", "Bretagne"), (39, "Jura", "Bourgogne Franche-Comté"),
    (16, "Charente", "Aquitaine-Limousin-Poitou-Charentes"), (94, "Val-de-Marne", "Île-de-France"), (40, "Landes", "Aquitaine-Limousin-Poitou-Charentes"), (45, "Loiret", "Centre-Val de Loire"), (90, "Territoire de Belfort", "Bourgogne Franche-Comté"),
    (71, "Saône-et-Loire", "Bourgogne-Franche-Comté"), (25, "Doubs", "Bourgogne-Franche-Comté"), (07, "Ardèche", "Auvergne-Rhône-Alpes"), (59, "Nord", "Hauts-de-France"), (50, "Manche", "Normandie"),
    (34, "Hérault", "Occitanie"), (29, "Finistère", "Bretagne"), (86, "Vienne", "Aquitaine-Limousin-Poitou-Charentes"), (93, "Seine-Saint-Denis", "Île-de-France"), (20, "Corse-du-Sud", "Corse"),
    (04, "Alpes-de-Haute-Provence", "Provence-Alpes-Côte d'Azur"), (79, "Deux-Sèvres", "Nouvelle-Aquitaine"), (87, "Haute-Vienne", "Aquitaine-Limousin-Poitou-Charentes"), (64, "Pyrénées-Atlantiques", "Nouvelle-Aquitaine"), (80, "Somme", "Nord-Pas-de-Calais Picardie"),
    (12, "Aveyron", "Languedoc-Roussillon Midi-Pyrénées"), (28, "Eure-et-Loir", "Centre-Val de Loire"), (18, "Cher", "Centre-Val de Loire"), (52, "Haute-Marne", "Alsace-Champagne-Ardenne-Lorraine"), (14, "Calvados", "Normandie"),
    (81, "Tarn", "Occitanie"), (03, "Allier", "Auvergne-Rhône-Alpes"), (66, "Pyrénées-Orientales", "Occitanie"), (05, "Hautes-Alpes", "Provence-Alpes-Côte d'Azur"), (10, "Aube", "Alsace-Champagne-Ardenne-Lorraine"),
    (77, "Seine-et-Marne", "Île-de-France"), (11, "Aude", "Occitanie"), (24, "Dordogne", "Aquitaine-Limousin-Poitou-Charentes"), (47, "Lot-et-Garonne", "Aquitaine-Limousin-Poitou-Charentes"), (61, "Orne", "Normandie"),
    (27, "Eure", "Normandie"), (40, "Landes", "Nouvelle-Aquitaine"), (36, "Indre", "Centre-Val de Loire"), (32, "Gers", "Occitanie"), (33, "Gironde", "Nouvelle-Aquitaine"),
    (41, "Loir-et-Cher", "Centre-Val de Loire"), (49, "Vendée", "Pays de la Loire"), (60, "Oise", "Hauts-de-France"), (65, "Hautes-Pyrénées", "Occitanie"), (55, "Meuse", "Alsace-Champagne-Ardenne-Lorraine"),
    (31, NULL, "Languedoc-Roussillon Midi-Pyrénées"), (67, "Bas-Rhin", "Grand Est"), (48, "Lozère", "Languedoc-Roussillon Midi-Pyrénées"), (10, "Aube", "Grand Est"), (09, "Ariège", "Occitanie"),
    (47, "Lot-et-Garonne", "Nouvelle-Aquitaine"), (88, "Vosges", "Grand Est"), (23, "Creuse", "Nouvelle-Aquitaine"), (23, "Creuse", "Aquitaine-Limousin-Poitou-Charentes"), (02, "Aisne", "Hauts-de-France"),
    (38, NULL, "Auvergne-Rhône-Alpes"), (58, "Nièvre", "Bourgogne Franche-Comté"), (08, "Ardennes", "Grand Est"), (86, "Vienne", "Nouvelle-Aquitaine"), (68, "Haut-Rhin", "Grand Est"),
    (89, "Yonne", "Bourgogne-Franche-Comté"), (39, "Jura", "Bourgogne-Franche-Comté"), (09, NULL, "Occitanie"), (46, "Lot", "Occitanie"), (24, "Dordogne", "Nouvelle-Aquitaine"),
    (16, "Charente", "Nouvelle-Aquitaine"), (62, "Pas-de-Calais", "Hauts-de-France"), (55, "Meuse", "Grand Est"), (44, "Vendée", "Pays de la Loire"), (51, "Marne", "Grand Est"),
    (NULL, "Puy-de-Dome", "Auvergne-Rhône-Alpes"), (87, "Haute-Vienne", "Nouvelle-Aquitaine"), (19, "Corrèze", "Nouvelle-Aquitaine"), (90, "Territoire de Belfort", "Bourgogne-Franche-Comté"), (12, "Aveyron", "Occitanie"),
    (70, "Haute-Saône", "Bourgogne-Franche-Comté"), (58, "Nièvre", "Bourgogne-Franche-Comté"), (21, "Côte-d'Or", "Bourgogne-Franche-Comté"), (47, NULL, NULL), (NULL, "Nord", "Hauts-de-France"),
    (14, "Calvados", "Normandy"), (NULL, "Maine-et-Loire", "Pays de la Loire"), (33, "Dordogne", "Aquitaine-Limousin-Poitou-Charentes"), (80, "Somme", "Hauts-de-France"), (73, NULL, NULL),
    (NULL, NULL, NULL), (48, "Lozère", "Occitanie"), (52, "Haute-Marne", "Grand Est"), (27, "Seine-Maritime", "Normandie"), (05, NULL, NULL),
    (31, NULL, NULL), (81, NULL, NULL), (26, NULL, NULL), (71, NULL, NULL), (13, NULL, NULL),
    (04, NULL, NULL), (38, "Drôme", "Auvergne-Rhône-Alpes"), (92, "Essonne", "Île-de-France"), (94, "Essonne", "Île-de-France"), (59, "Pas-de-Calais", "Nord-Pas-de-Calais Picardie"),
    (95, "Yvelines", "Île-de-France"), (72, NULL, NULL), (66, NULL, NULL), (83, NULL, NULL), (53, NULL, "Pays de la Loire"),
    (83, "Var", NULL), (01, "Rhône", "Auvergne-Rhône-Alpes"), (56, "Morbihan", NULL), (51, "Aisne", "Nord-Pas-de-Calais Picardie"), (16, NULL, "Aquitaine-Limousin-Poitou-Charentes"),
    (47, NULL, "Aquitaine-Limousin-Poitou-Charentes"), (14, NULL, "Normandie"), (22, "Côtes-d'Armor", NULL), (33, NULL, NULL), (02, NULL, "Nord-Pas-de-Calais Picardie"),
    (75, "Arrondissement de Paris", "Île-de-France"), (81, "Haute-Garonne", "Languedoc-Roussillon Midi-Pyrénées"), (57, NULL, "Alsace-Champagne-Ardenne-Lorraine"), (42, "Haute-Loire", "Auvergne-Rhône-Alpes"), (31, "Gers", "Languedoc-Roussillon Midi-Pyrénées"),
    (89, NULL, NULL), (84, NULL, NULL), (75, "Département de Paris", "Île-de-France"), (43, NULL, NULL), (35, NULL, NULL),
    (19, NULL, NULL), (38, NULL, NULL), (NULL, "Gers", "Occitanie"), (56, "Morbihan", "Brittany"), (NULL, "Seine-Maritime", "Normandy"),
    (NULL, "Lot-et-Garonne", "Nouvelle-Aquitaine"), (33, "Dordogne", "Nouvelle-Aquitaine"), (NULL, "Territoire de Belfort", "Bourgogne-Franche-Comté"), (09, "Ariege", "Occitanie"), (29, "Finistere", "Brittany"),
    (22, "Côtes-d'Armor", "Brittany"), (78, NULL, NULL), (63, "Puy-de-Dome", "Auvergne-Rhône-Alpes"), (NULL, "Finistere", "Brittany");
