use projet_cir2;
-- _______________________ Annees __________________________--
INSERT INTO `annee`(`num_annee`)
VALUES
    (2007),
    (2008),
    (2006),
    (2005),
    (2010),
    (2000),
    (2011),
    (2003),
    (2009),
    (2017),
    (2002),
    (2004),
    (1999),
    (1998),
    (1996),
    (2012),
    (2016),
    (2013),
    (2015),
    (2014),
    (2020),
    (2019),
    (2018),
    (2022),
    (2021),
    (2023),
    (1993),
    (1997),
    (2001),
    (1990);
-- _______________________ Installateurs __________________________--
INSERT INTO `installateur`(`nom`)
VALUES
    ("MECOTECH"),
    ("Hugo Solaire"),
    ("A+ Services, 26260 MARGES"),
    ("Photovolta&amp;amp;amp;iuml;que 83"),
    ("ENERGIE VERTE DE FRANCE"),
    ("SARTHE SOLAIRE BROSSIER"),
    ("Olysi");
-- _______________________ Marques Onduleurs __________________________--
INSERT INTO `marque_ondu`(`marque`)
VALUES
    ("SMA"),
    ("Mastervolt"),
    ("Sputnik"),
    ("Enphase Energy"),
    ("CONERGY"),
    ("Tenesol"),
    ("Fronius"),
    ("KACO"),
    ("Photowatt"),
    ("Solax"),
    ("Power-One"),
    ("Total Energie"),
    ("ABB"),
    ("EFFEKTA"),
    ("Siemens"),
    ("Schuco"),
    ("Solwex"),
    ("Solarstocc"),
    ("AEG"),
    ("Growatt"),
    ("Schneider electric"),
    ("SHARP"),
    ("Steca"),
    ("Pas_dans_la_liste_onduleur"),
    ("Diehl AKO"),
    ("General Electric"),
    ("Sunways"),
    ("Mitsubishi"),
    ("Solarmax"),
    ("Delta Energy"),
    ("Victron"),
    ("Oelmaier"),
    ("Sunset"),
    ("Kostal"),
    ("POWERSTOC"),
    ("SolarEdge"),
    ("BP Solar / Trace"),
    ("Danfoss"),
    ("Xantrex"),
    ("AERO SHARP"),
    ("ibc solar"),
    ("Ingeteam"),
    ("ATERSA"),
    ("SolarWorld"),
    ("Eaton Corporation"),
    ("Sunny Swiss"),
    ("Suntechnics"),
    ("INFOSEC"),
    ("DELTA Electronics"),
    ("Sanyo"),
    ("Aunilec"),
    ("Thomson"),
    ("AXUN"),
    ("solar"),
    ("Wurth Solar"),
    ("MPP SOLAR"),
    ("Solaire Direct"),
    ("Solutronic"),
    ("Omnik"),
    ("SunPower"),
    ("bejing kinglong"),
    ("SOCOMEC"),
    ("AURORA"),
    ("ACE"),
    ("Motech"),
    ("Phoenixtec"),
    ("EVERSOL"),
    ("Enecsys"),
    ("GE Energy"),
    ("Solaxpower"),
    ("VOLTEA"),
    ("APS - APSystems"),
    ("FAGOR"),
    ("HUAWEI"),
    ("Riello"),
    ("Carlo Gavazzi"),
    ("SUNGROW"),
    ("soladin"),
    ("Solon AG"),
    ("Latronic"),
    ("Cotek"),
    ("Powercom"),
    ("Outback Power System"),
    ("Ainelec"),
    ("EnerSolis"),
    ("SUNSYS"),
    ("Solar-Fabrik"),
    ("Studer"),
    ("EVERLIGHT"),
    ("S2S"),
    ("Samil Power"),
    ("IBC Solar AG"),
    ("LTI"),
    ("WKS"),
    ("Ubbink"),
    ("Centrolar"),
    ("Bourgeoisglobal"),
    ("Involar"),
    ("Santerno"),
    ("DURALUX"),
    ("Opti-Solar"),
    ("Aros"),
    ("Kinglong"),
    ("Voltronic Power"),
    ("Kyocera"),
    ("Aixcon"),
    ("REFU"),
    ("I-Energy"),
    ("KaiDeng Energy"),
    ("IMEON"),
    ("GINLONG"),
    ("Power Solutions"),
    ("Alpha"),
    ("Photoelectric"),
    ("Grid Tie Inverter"),
    ("Energetica"),
    ("Omron"),
    ("Nedap Energy"),
    ("Hoymiles"),
    ("Aeconversion"),
    ("NETek"),
    ("Projoy Electric"),
    ("Satcon"),
    ("Colas"),
    ("PCM"),
    ("Philips"),
    ("Connect Energy"),
    ("Wurth Solergy"),
    ("Exendis"),
    ("Suntension"),
    ("Bahrmann"),
    ("Beacon"),
    ("Talesun"),
    ("SoFar Solar"),
    ("TRITEC"),
    ("Solar Konzept"),
    ("Siliken"),
    ("PV Powered"),
    ("Siac-Soleil"),
    ("Invertomatic"),
    ("ASP"),
    ("EAI"),
    ("BEON ENERGY"),
    ("saj-electric"),
    ("Imeon Energy"),
    ("Envertech"),
    ("UFE"),
    ("CLIPSOL"),
    ("Courtois"),
    ("Huayu New Energy Technologies"),
    ("Trace"),
    ("EPEVER"),
    ("Goodwe"),
    ("Hangzhou Zhejiang");
-- _______________________ Marques Panneaux __________________________--
INSERT INTO `marque_pan`(`marque`)
VALUES
    ("Sanyo"),
    ("Canadian Solar"),
    ("Mitsubishi"),
    ("Schuco"),
    ("Roto Frank"),
    ("Kyocera"),
    ("CONERGY"),
    ("Solar-Fabrik"),
    ("SHARP"),
    ("KIOTO"),
    ("Tenesol"),
    ("Imerys"),
    ("TRINA SOLAR"),
    ("SOLVIS"),
    ("Photowatt"),
    ("DAXTEC"),
    ("Istar Solar"),
    ("SUNTECH"),
    ("Solarfun"),
    ("BP Solar"),
    ("Solon AG"),
    ("Schott"),
    ("Solarwatt"),
    ("YOCASOL"),
    ("AlfaSolar"),
    ("Solara"),
    ("Biohaus"),
    ("Total Energie"),
    ("Solarcentury"),
    ("Siemens Solar"),
    ("Wurth Solar"),
    ("Solarstocc"),
    ("Viessmann"),
    ("Solarwood"),
    ("Solaris"),
    ("Shell Solar"),
    ("Pas_dans_la_liste_panneaux"),
    ("Helios Technology"),
    ("Ensol"),
    ("Energy Solutions"),
    ("Siliken"),
    ("SOLEOS"),
    ("Issol"),
    ("SolarWorld"),
    ("CEEG"),
    ("Auversun"),
    ("BIO ENERGY"),
    ("Sulfurcell"),
    ("SunPower"),
    ("ET Solar"),
    ("Sunasol"),
    ("ibc solar"),
    ("Unimetal"),
    ("ALEO"),
    ("Ecostream"),
    ("Bosch"),
    ("Uni-Solar"),
    ("NAPS"),
    ("Solar swiss"),
    ("AXITEC"),
    ("Baoding Yingli"),
    ("Sunearth"),
    ("SCHEUTEN"),
    ("MHI"),
    ("SOLSTIS"),
    ("Sopray Solar"),
    ("SILLIA"),
    ("DUALSUN"),
    ("ARCO SOLAR"),
    ("SCN Energy"),
    ("3S"),
    ("ATERSA"),
    ("Photovoltech"),
    ("EGing"),
    ("Centrosolar"),
    ("Eurener"),
    ("Evergreen"),
    ("Mitsubishi Heavy"),
    ("SY SOL"),
    ("BiSol"),
    ("GE Energy"),
    ("Heliene"),
    ("BIOSOL"),
    ("Mylight Systems"),
    ("Shunda"),
    ("S-ENERGY"),
    ("Azur Solar"),
    ("Solar Creator"),
    ("Enfinity"),
    ("Fuji Electric"),
    ("CLIPSOL"),
    ("Rec Solar"),
    ("Ubbink"),
    ("Elysun"),
    ("Shanghai Chaori"),
    ("Renewis"),
    ("Isofoton"),
    ("DS Solar"),
    ("Alliantz"),
    ("Heckert Solar"),
    ("CP SOLAR"),
    ("Jetion"),
    ("SolarTechnics"),
    ("Koramic"),
    ("Benqsolar"),
    ("SUN TECHNOLOGY"),
    ("Ulica"),
    ("Luxor"),
    ("SOLAR FRONTIER"),
    ("Akhter"),
    ("Solar excellence"),
    ("French Energy"),
    ("ZYTECH"),
    ("ReneSola"),
    ("CNPV"),
    ("SYSTOVI"),
    ("FRANCEWATTS"),
    ("SINSKI"),
    ("Yingli Solar"),
    ("Amerisolar"),
    ("kdgenergy"),
    ("DelSolar"),
    ("Kaneka"),
    ("Sun Tech Solar"),
    ("Perlight Solar"),
    ("Fonroche / Pevafersa"),
    ("Sunny Swiss"),
    ("Sunset"),
    ("Korax"),
    ("GH Solar"),
    ("UPSOLAR"),
    ("Cristal Solar"),
    ("DREAMSOL"),
    ("I-SONNE"),
    ("Midi Solaire"),
    ("S.A.G."),
    ("Xgroup"),
    ("FIRE ENERGY"),
    ("Saint Gobain Solar"),
    ("WORLWIDE ENERGY AND MANUFACTURING"),
    ("Solar Power"),
    ("REC Scanmodule"),
    ("SUN ENERGIE"),
    ("CNBM Solar"),
    ("Solaire Direct"),
    ("CSUN"),
    ("Sunage"),
    ("Integra Solar"),
    ("French Solar Industry"),
    ("Voltec Solar"),
    ("Sunrise"),
    ("Emmvee solar"),
    ("Sunlink PV"),
    ("FATH Solar"),
    ("WOLT TEKNOLOGY"),
    ("SOLAIRE ELEC"),
    ("HYUNDAI"),
    ("robby solar"),
    ("SunnyPower"),
    ("ENR PRO"),
    ("O2 Solar"),
    ("Consolar"),
    ("ZNShine"),
    ("Ningbo"),
    ("HelioSphera"),
    ("SOLASUN"),
    ("3A Energies"),
    ("centro solar"),
    ("ALKASOL"),
    ("SOLSONICA"),
    ("Brisban Solar"),
    ("Solar tendances"),
    ("AviraSolar"),
    ("Solea"),
    ("ght energy"),
    ("Latitude Solar"),
    ("ALTERNASOL"),
    ("system photonics"),
    ("REC"),
    ("UE Solar"),
    ("SNA Solar"),
    ("kvazar"),
    ("S Energy"),
    ("Q-cells"),
    ("FRANKFORT SOLAR"),
    ("Telecom-STV"),
    ("IM SOLAR"),
    ("Romag"),
    ("SUN ENERGY"),
    ("Eoplly"),
    ("Yohkon"),
    ("SoluxTec"),
    ("Shanghai Topsolar"),
    ("GSS / IPEG"),
    ("MHH"),
    ("SUNY SYSTEM"),
    ("ECSOLAR"),
    ("EDF"),
    ("Soleia"),
    ("Solibro"),
    ("Siligem"),
    ("Europ-Solar"),
    ("LONGI Solar"),
    ("Moser Baer"),
    ("FT Solaire"),
    ("AVASOL"),
    ("Giordano"),
    ("Mage Solar"),
    ("JC SOLAR"),
    ("GSDF"),
    ("Hanwha SolarOne"),
    ("Wurth-Solar"),
    ("CP-Solar"),
    ("Metrotile"),
    ("Serrano Environnement"),
    ("JINKO SOLAR"),
    ("GEG AG"),
    ("SunOwe"),
    ("Win Win Precision"),
    ("Daqo New Energy"),
    ("Caldeis"),
    ("Schwaben Solar"),
    ("Activasun"),
    ("PHOTON POWER"),
    ("UBINK"),
    ("Watt Home"),
    ("Solareole"),
    ("FreeSuntec"),
    ("LIBRA ENERGY"),
    ("LC Solar"),
    ("HELIOS ENERGY"),
    ("Sunways"),
    ("NEXPOWER"),
    ("CS WISMAR"),
    ("CSG Solar AG"),
    ("Sunova Solar"),
    ("Union Solar"),
    ("Panasonic"),
    ("SARONIC"),
    ("First solar"),
    ("GPV"),
    ("Asola"),
    ("Antaris Solar"),
    ("SETA"),
    ("Alex Solar"),
    ("Intertechnology"),
    ("Astronergy"),
    ("Pramac"),
    ("Solartec"),
    ("GESOLAR"),
    ("MX Group"),
    ("Oryon"),
    ("JA Solar"),
    ("FoVo Handles"),
    ("First Hybrid Energy"),
    ("APRISUN"),
    ("Thomson Energy"),
    ("GREEN EARTH"),
    ("Zhongjing Solar"),
    ("Topper Sun"),
    ("GSS"),
    ("AIDE SOLAR"),
    ("Hareon Solar"),
    ("LG Electronics"),
    ("Advent"),
    ("Ningbo Qixin Solar"),
    ("Exiom"),
    ("Solar Cells"),
    ("BYD"),
    ("Sovello"),
    ("DATATSP"),
    ("SunFlower"),
    ("RECOM"),
    ("Elsingor"),
    ("Alwitra"),
    ("FotoTherm"),
    ("CAPTELIA"),
    ("Solarezo"),
    ("AMP Solar"),
    ("IATSO"),
    ("MSK Corporation"),
    ("EliFrance"),
    ("Next Generation"),
    ("Suntechnics"),
    ("Atlantis Energie"),
    ("LONG ENERGY"),
    ("Jiangsu Wanfeng"),
    ("JMS"),
    ("Phono Solar"),
    ("LDK SOLAR"),
    ("AEG"),
    ("Bourgeoisglobal"),
    ("SolarEdge"),
    ("AU O"),
    ("Samsung Electronics"),
    ("ZG - Cells"),
    ("Xi an Huanghe"),
    ("Zhejiang ZG-Cells"),
    ("SyneXium"),
    ("Italsolar"),
    ("BELGASUN"),
    ("SCHUTTEN-SOLAR"),
    ("PV Enterprise"),
    ("Solaria Energia"),
    ("ALDEN"),
    ("FUTURASUN"),
    ("S. E. Project"),
    ("USL"),
    ("BLDSolar"),
    ("Universal Energy"),
    ("Tournaire"),
    ("ITS Innotech Solar"),
    ("UNAH"),
    ("833 Solar"),
    ("DOMOS Industries"),
    ("GENERIQUE"),
    ("Unisolar"),
    ("German PV"),
    ("Francilienne"),
    ("AXUN"),
    ("apinsolar"),
    ("Intersolar"),
    ("Suneasy"),
    ("Algatec Solar"),
    ("Almasolar"),
    ("SolarfunBENQ"),
    ("Solarstoxx"),
    ("kingdomsolar"),
    ("Elite Solar"),
    ("UNIMEN SOLAR"),
    ("AUO AU Optronics Corporation"),
    ("THALEOS"),
    ("A Solar"),
    ("GPPV"),
    ("BEIJING PROFLEX"),
    ("Solarex"),
    ("GAHELIOS"),
    ("Pacific Solar Tech"),
    ("VMH-ENERGIE"),
    ("Aimex"),
    ("LORENTZ"),
    ("ASE"),
    ("ORI Solar"),
    ("SENTECH"),
    ("ErSol"),
    ("Inventux"),
    ("Hitachi"),
    ("Colas"),
    ("HC Solar Power"),
    ("SOLPOWER"),
    ("CAPTELIA "),
    ("Arco / Siemens"),
    ("Solarwerk"),
    ("Phoenix Solar"),
    ("Ansaldo"),
    ("Solarinox"),
    ("Shanghai"),
    ("SYSTAIC"),
    ("Signet Solar Inc"),
    ("China solarland"),
    ("SES"),
    ("Chinaland Solar Energy"),
    ("Ammini Solar"),
    ("Stefan Nau"),
    ("Jiangxi Best Solar"),
    ("GPPV (Greenpower)"),
    ("Zhejiang RDM"),
    ("Gloria Solar"),
    ("Solarday"),
    ("AstroPower"),
    ("stream solar"),
    ("Free Energy"),
    ("Soleole"),
    ("Droben"),
    ("FVG ENERGY"),
    ("BHEL"),
    ("DAY4ENERGY"),
    ("TESUN"),
    ("PVT Austria"),
    ("QS SOLAR"),
    ("Himin Solar"),
    ("Solarnova"),
    ("KL Solar"),
    ("Rheinzink"),
    ("Enertech"),
    ("cuantum solar"),
    ("Jinhua Dokio"),
    ("sunworx-solar"),
    ("Ultimate solar"),
    ("Beem Energy"),
    ("Depasol"),
    ("Solel"),
    ("Powerlight"),
    ("URE"),
    ("SUNERG"),
    ("SUNPRO"),
    ("Antec-Solar"),
    ("Symphony En."),
    ("Sonnenstromfabrik"),
    ("Risun"),
    ("SUNOLOGY"),
    ("EniTecnologie"),
    ("SOLAR ONE"),
    ("URECO"),
    ("Voltus"),
    ("LUXOL"),
    ("ECOWATT"),
    ("Solutium"),
    ("JNL"),
    ("PEIMAR"),
    ("ECO DELTA"),
    ("Sonnex"),
    ("RAYS"),
    ("NORWATT"),
    ("DMEGC"),
    ("Siemens/Shell"),
    ("Terrasolar"),
    ("DUOenergy"),
    ("Omnis Power"),
    ("SUNOLOGIE"),
    ("ESPY"),
    ("RISEN-SOLAR"),
    ("Trimex Tesla"),
    ("MEYER BURGER"),
    ("Hengji Solar");
-- _______________________ Mois __________________________--
INSERT INTO `mois`(`num_mois`)
VALUES
    (1), (2), (3), (4), (5), (6), (7), (8), (9), (10), (11), (12);
-- _______________________ Marques Regions __________________________--
INSERT INTO `region`(`nom_region`)
VALUES
    ("Occitanie"),
    ("Languedoc-Roussillon Midi-Pyrénées"),
    ("Auvergne-Rhône-Alpes"),
    ("Pays de la Loire"),
    ("Provence-Alpes-Côte d'Azur"),
    ("Grand Est"),
    ("Île-de-France"),
    ("Bourgogne Franche-Comté"),
    ("Aquitaine-Limousin-Poitou-Charentes"),
    ("Nord-Pas-de-Calais Picardie"),
    ("Bretagne"),
    ("Normandie"),
    ("Alsace-Champagne-Ardenne-Lorraine"),
    ("Corse"),
    ("Centre-Val de Loire"),
    ("Nouvelle-Aquitaine"),
    ("Bourgogne-Franche-Comté"),
    ("Hauts-de-France"),
    ("Normandy"),
    ("Brittany");